/*
 * generated by Xtext 2.17.0
 */
package org.iaas.toscaYaml.ide.contentassist.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.iaas.toscaYaml.ide.contentassist.antlr.internal.InternalYamlParser;

public class YamlTokenSource extends AbstractIndentationTokenSource {

	public YamlTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalYamlParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalYamlParser.RULE_INDENT;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalYamlParser.RULE_DEDENT;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
