/*
 * generated by Xtext 2.17.0
 */
package org.iaas.toscaYaml.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.iaas.toscaYaml.yaml.Yaml
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(YamlInjectorProvider)
class YamlParsingTest {
	@Inject
	ParseHelper<Yaml> parseHelper
	
	@Test
	def void loadModel() {
		
	}
}
