/*
 * generated by Xtext 2.17.0
 */
package org.iaas.toscaYaml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class YamlStandaloneSetup extends YamlStandaloneSetupGenerated {

	def static void doSetup() {
		new YamlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
