/*
 * generated by Xtext 2.17.0
 */
package org.iaas.toscaYaml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class YamlRuntimeModule extends AbstractYamlRuntimeModule {
}
