/*
 * generated by Xtext 2.17.0
 */
package org.iaas.toscaYaml.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.iaas.toscaYaml.YamlRuntimeModule
import org.iaas.toscaYaml.YamlStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class YamlIdeSetup extends YamlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new YamlRuntimeModule, new YamlIdeModule))
	}
	
}
